Start writing relnotes for v23.24
EnterpriseDB/tpa pull request #44
Opened 2023-10-12 10:27 UTC by amenonsen

main

2023-10-16 12:19 UTC, haroon-github requested changes

2023-10-16 12:19 UTC, haroon-github commented on RELNOTES.md
> +  be removed in a future release.
We should link to the detailed section in docs that explains the impact from this change

2023-10-17 13:02 UTC, haroon-github approved these changes

2023-10-17 13:02 UTC, gonzalemario approved these changes

2023-10-17 13:05 UTC, merged