Add explicit ownership and mode to steps affecting filesystem objects
EnterpriseDB/tpa pull request #57
Opened 2023-11-03 12:47 UTC by jdnevin

Add quotes to mode octals to avoid Ansible risky-octal linting

2023-11-03 12:58 UTC, gonzalemario requested changes

2023-11-03 12:58 UTC, gonzalemario commented on roles/haproxy/config/tasks/main.yml
There are four comments starting with XXX that doesn't go along with the rest of file. I think we should remove them from this changeset.

other than that, lgtm!

2023-11-23 05:23 UTC, amenonsen commented on roles/repmgr/common/tasks/main.yml
> +    - {mode: ""0755"", path: follow_command.sh}
?!

2023-11-23 05:24 UTC, amenonsen commented on roles/sys/repositories/tasks/os/Debian/repositories.yml
> +    mode: "{{ needs_auth|ternary('0600', '"0644"') }}"
This is not correct.

2023-12-18 14:53 UTC, gonzalemario approved these changes

2023-12-18 15:09 UTC, merged